Completed the team section
winhacks/2024-website pull request #7
Opened 2023-12-07 23:26 UTC by oyousef25

![image](https://github.com/winhacks/2024-website/assets/71517267/fd2fc5bc-a2c3-414f-ae03-ef13a4eafebf)

2023-12-08 20:10 UTC, jere-mie requested changes
Please remove all of the unnecessary .idea/ stuff. Also, I think you used a formatter or something which changed pretty much everything in the index.html file, so there's no way for me to see what you actually changed

2023-12-14 22:55 UTC, oyousef25 commented
I removed the unnecessary files lol. Ooof yes my files get automatically formatted when I click ctrl + s. let me know if you want me to redo the section with the old index.html code format

2023-12-15 01:14 UTC, jere-mie commented
it's fine @oyousef25. In the future though, I'd recommend just using VSCode for this repo in particular. You won't need any fancy IDE features, and you won't have to watch out for accidentally committing extra files.

You should also keep an eye on what you're committing/pushing. Don't just default to adding and committing all git changes - you should manually select which files you'd like to add/commit/push, that way only relevant stuff gets added to git repos.


None of this advice is at all important for this repo, but it'll help a ton when collaborating on larger codebases with more maintainers

2023-12-15 01:14 UTC, jere-mie approved these changes

2023-12-15 01:14 UTC, merged